/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.files;

import config.Config;
import java.io.File;
import utiles.Compresion;
import utiles.Dialogos;
import utiles.PanelModal;

/**
 *
 * @author ado
 */
public class PanelAbrirProyecto extends PanelModal<String> {

    /**
     * Creates new form Files
     */
    public PanelAbrirProyecto(){
        super("Abrir Proyecto");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nota: Si el directorio ya existe no creara un nuevo proyecto, asumira que ya existe.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(0, 15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:

        if(evt.getActionCommand().compareTo("ApproveSelection") == 0)
        {
            File f = jFileChooser1.getSelectedFile();
            
            String path = f.getPath();

            if(!f.exists())
            {
                if(!f.mkdir())
                {
                    Dialogos.showMessageDialog("no se pudo crear el directorio");
                    return;
                }

                try {
                    Compresion.unzip(Config.PROYECT_TEMPLATE_ZIP_PATH, f);

                } catch (Exception e) {
                    Dialogos.showMessageDialog("No se pudo descomprimir el zip del nuevo proyecto " + e.getMessage());
                    return;
                }
            }
            else if(!f.isDirectory())//en caso de que el componente no este configurado solo para directorios.
            {
                Dialogos.showMessageDialog("no es un directorio");
                return;
            }

            result = path;
        }
        close();
    }//GEN-LAST:event_jFileChooser1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
