/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles.variables;

import config.Config;
import java.util.ArrayList;
import java.util.HashMap;
import php.utiles.ArrayCodeCreator;
import utiles.ComboBoxBasicManager;
import comaseparatedparser.CommaSeparatedExtractor;
import utiles.Dialogos;
import utiles.InputOutput;
import utiles.PanelModal;
import variables.EnumBasico;
import variables.Variable;
import variables.VariableIO;

/**
 *
 * @author ado
 */
public class PanelVariableEditor extends PanelModal<Variable> {
    private final String final_input_variable;

    /**
     * Creates new form PanelVariableEditor
     */
    public PanelVariableEditor(String var_name) throws Exception {
        super("Editor de variable");
        initComponents();
        
        this.final_input_variable = var_name;
        
        ComboBoxBasicManager combo_mgr = new ComboBoxBasicManager(jComboBoxTypes);
        
        combo_mgr.init();
        
        for(EnumBasico e : EnumBasico.values())
        {
            combo_mgr.addItem(e.toString());
        }
        
        if(final_input_variable!= null)
        {
            jTextVarName.setText(final_input_variable);
            jTextVarName.setEnabled(false);
            
            loadVariable();//este asigna valores a los controles, el combobox tiene que estar configurado antes!!!
        }
        else
        {
            jButtonEliminar.setEnabled(false);
        }
    }
    
    private void loadVariable() throws Exception
    {
        Variable v = Config.getInstance().getVariableIO_newInstance().getVariable(final_input_variable);
        
        jTextVarName.setText(v.getName());
        jTextComment.setText(v.getDescripcion());
        jTextPaneD_value.setText(v.getD_value());
        
        if(v.getTipo().getFields() != null && v.getTipo().getFields().length > 0)
            jTextFields.setText(String.join(",", v.getTipo().getFields()));
        
        jComboBoxTypes.setSelectedItem(v.getTipo().getTipoBasico().toString());
    }
    
    /**
     * Consulta el combobox para saber si la variable es de tipo array
     */
    private boolean isType_Array()
    {
        return jComboBoxTypes.getSelectedItem().toString().compareTo(EnumBasico.ARRAY.toString()) == 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemConvertComaSeparated = new javax.swing.JMenuItem();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jTextVarName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextComment = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFields = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTypes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneD_value = new javax.swing.JTextPane();

        jMenuItemConvertComaSeparated.setText("Convert comma separated");
        jMenuItemConvertComaSeparated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConvertComaSeparatedActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemConvertComaSeparated);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");

        jLabel1.setText("var_name:");

        jLabel2.setText("comment:");

        jLabel3.setText("d_value (codigo php para asignacion, ej: strings con comillas):");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("fields:");

        jLabel5.setText("type:");

        jComboBoxTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextPaneD_value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPaneD_value.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPaneD_valueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPaneD_value);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextComment))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonEliminar)
                                .addGap(0, 210, Short.MAX_VALUE))
                            .addComponent(jTextVarName)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextVarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        try {
            String var_name = InputOutput.getString(jTextVarName, "valor de var_name invalido");
            String comment = jTextComment.getText();
            String d_value = jTextPaneD_value.getText();
            
            ComboBoxBasicManager combo_mgr = new ComboBoxBasicManager(jComboBoxTypes);
            
            String type = combo_mgr.getValue("valor de type invalido");
            
            Variable v;
            
            if(type.compareTo(EnumBasico.ARRAY.toString()) == 0)
            {
                String[] fields = InputOutput.getSplit(jTextFields, null);
                
                v = new Variable(var_name, comment, type, d_value, fields);
            }
            else
            {
                v = new Variable(var_name, comment, type, d_value, null);
            }
            
            VariableIO io = Config.getInstance().getVariableIO_newInstance();
            
            if(final_input_variable == null)
            {   
                io.addVariable(v);
            }
            else
            {
                io.saveVariable(v);
            }
            
            io.saveFile();
            
            close();
            
        } catch (Exception e) {
            Dialogos.showMessageDialog(e.getMessage());
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jComboBoxTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypesActionPerformed
        // TODO add your handling code here:
        if(isType_Array())
        {
            jTextFields.setEnabled(true);
        }
        else
        {
            jTextFields.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxTypesActionPerformed

    private void jTextPaneD_valueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPaneD_valueMouseClicked
        // TODO add your handling code here:
        
        if(evt.getButton() == 3)
            jPopupMenu1.show(jTextPaneD_value, evt.getX(), evt.getY());
        
    }//GEN-LAST:event_jTextPaneD_valueMouseClicked

    private void jMenuItemConvertComaSeparatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConvertComaSeparatedActionPerformed
        // TODO add your handling code here:
        String text = jTextPaneD_value.getText();
        String[] fields = null;
        
        try {
            ArrayList<HashMap<String, String>> alist_fields = new CommaSeparatedExtractor(jTextFields.getText(), null).parse();
            
            fields = new String[alist_fields.size()];
            
            for (int i = 0; i < fields.length; i++) {
                fields[i] = alist_fields.get(i).get(CommaSeparatedExtractor.SINGLEITEMINDICATOR);
            }
            
        } catch (Exception e) {
            Dialogos.showMessageDialog("Problema con los fields: " + e.getMessage());
            return;
        }
        
        try {
            
            CommaSeparatedExtractor conv = new CommaSeparatedExtractor(text, fields);
            
            ArrayCodeCreator c = new ArrayCodeCreator(conv.parse(), CommaSeparatedExtractor.SINGLEITEMINDICATOR);
            
            jTextPaneD_value.setText(c.create());
            
        } catch (Exception e) {
            Dialogos.showMessageDialog(e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemConvertComaSeparatedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItemConvertComaSeparated;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextComment;
    private javax.swing.JTextField jTextFields;
    private javax.swing.JTextPane jTextPaneD_value;
    private javax.swing.JTextField jTextVarName;
    // End of variables declaration//GEN-END:variables
}
